CREATE DATABASE uni;
use uni;
CREATE TABLE num(id int);
SELECT*FROM num;
INSERT INTO num VALUES(1);
INSERT INTO num VALUES(2);
INSERT INTO num VALUES(3);
INSERT INTO num VALUES(4);
INSERT INTO num VALUES(5);
INSERT INTO num VALUES(6);
INSERT INTO num VALUES(7);

CREATE TABLE num1(Id int);
INSERT INTO num1 VALUES(7);
INSERT INTO num1 VALUES(6);
INSERT INTO num1 VALUES(5);
INSERT INTO num1 VALUES(4);
INSERT INTO num1 VALUES(3);
INSERT INTO num1 VALUES(2);
INSERT INTO num1 VALUES(1);
SELECT  * FROM num1 ;
SELECT *FROM num UNION SELECT *FROM num1 order by id; 

